### ISSUE TITLE
Watch out for .IndexOf("\0") it will not work in .net core 

### ISSUE THREAD

**Issue by AsoftDev** [wwwMADwww/FTD2XX_DotNetCoreWrapper#1]
.IndexOf("\0")  should be changed to .IndexOf('\0') 
See
https://github.com/dotnet/runtime/issues/46569

**Comment by wwwMADwww** [comment]
Fixed, thank you. Actually FTDI fixed it about two years ago https://ftdichip.com/software-examples/code-examples/csharp-examples/ , my version of this wrapper is very old.
